name: distuv
description: univariate random distributions sampling and statistics forked from grizzly_distuv
version: 1.1.0
homepage: https://github.com/Grizzly-dart/grizzly_stats

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:

dev_dependencies:
  test:
  grizzly_range: ^3.0.0