name: grizzly_distuv
description: Univariate random distributions library for Dart
version: 1.1.0
homepage: https://github.com/Grizzly-dart/grizzly_stats

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:

dev_dependencies:
  test:
  grizzly_range: ^3.0.0